#!/usr/bin/env ruby

if ARGV.length == 2
  first = File.read(ARGV.shift).split("\n")
else
  first = STDIN.read.split("\n")
end

last = File.read(ARGV.shift).split("\n")

puts (first - last).join("\n")
